-- MySQL Script generated by MySQL Workbench
-- Wed Aug 13 12:05:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NULL AUTO_INCREMENT,
  `Nome completo` VARCHAR(70) NOT NULL,
  `Celular` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(20) NOT NULL,
  `Endereco` VARCHAR(45) NULL,
  `datanascimento` DATE NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vendas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `IDcliente` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  `Clientes_idClientes` INT NOT NULL,
  `historicodevendas` DATE NULL,
  PRIMARY KEY (`idVendas`),
  CONSTRAINT `fk_Vendas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vendas_Clientes1_idx` ON `mydb`.`Vendas` (`Clientes_idClientes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(60) NOT NULL,
  `Tipojoia` VARCHAR(60) NULL,
  `Materialjoia` VARCHAR(60) NULL,
  `Fornecedor` VARCHAR(60) NULL,
  `Quantidadeestoque` INT NULL,
  `Preco` DECIMAL(30) NULL,
  `Vendas_idVendas` INT NOT NULL,
  PRIMARY KEY (`idProdutos`),
  CONSTRAINT `fk_Produtos_Vendas1`
    FOREIGN KEY (`Vendas_idVendas`)
    REFERENCES `mydb`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produtos_Vendas1_idx` ON `mydb`.`Produtos` (`Vendas_idVendas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `Nomedoproduto` VARCHAR(70) NULL,
  `datacadastro` DATE NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`idEstoque`),
  CONSTRAINT `fk_Estoque_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estoque_Produtos1_idx` ON `mydb`.`Estoque` (`Produtos_idProdutos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedores` (
  `idFornecedores` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(20) NULL,
  `Email` VARCHAR(20) NOT NULL,
  `Celular` VARCHAR(20) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos_has_Fornecedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produtos_has_Fornecedores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Produtos_has_Fornecedores` (
  `Produtos_idProdutos` INT NOT NULL,
  `Fornecedores_idFornecedores` INT NOT NULL,
  PRIMARY KEY (`Produtos_idProdutos`, `Fornecedores_idFornecedores`),
  CONSTRAINT `fk_Produtos_has_Fornecedores_Produtos`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Fornecedores_Fornecedores1`
    FOREIGN KEY (`Fornecedores_idFornecedores`)
    REFERENCES `mydb`.`Fornecedores` (`idFornecedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produtos_has_Fornecedores_Fornecedores1_idx` ON `mydb`.`Produtos_has_Fornecedores` (`Fornecedores_idFornecedores` ASC) VISIBLE;

CREATE INDEX `fk_Produtos_has_Fornecedores_Produtos_idx` ON `mydb`.`Produtos_has_Fornecedores` (`Produtos_idProdutos` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
